id: I4596B59B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:53:06+00:00'
last_modified: '2022-06-07T21:37:05.323248+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25180
  title: ཀརྨ་སི་ཏུའི་སུམ་རྟགས་འགྲེལ་ཆེན་མཁས་པའི་མགུལ་རྒྱན་མུ་རིག་འཕྲེང་མཛེས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4790':
      image_group_id: I1KG25182
      title: ''
      total_pages: 218
      order: 1
      base_file: 4790.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
