id: I4596B59B
legacy_id: P004276
ocr_import_info:
  bdrc_scan_id: W1KG25180
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T15:51:33'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T14:09:13.791044+00:00'
last_modified: 2022-08-31 22:09:24.968468
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG25180
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG25180
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀརྨ་སི་ཏུའི་སུམ་རྟགས་འགྲེལ་ཆེན་མཁས་པའི་མགུལ་རྒྱན་མུ་རིག་འཕྲེང་མཛེས།
  author: སི་ཏུ་ཆོས་ཀྱི་འབྱུང་གནས།
statistics:
  ocr_word_mean_confidence_index: 0.6837166143720814
  ocr_word_median_confidence_index: 0.9399999976158142
quality: null
bases:
  I1KG25182:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG25182
      total_pages: 218
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG25182.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.6837166143720814
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
