id: P004276
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25180
  title: ཀརྨ་སི་ཏུའི་སུམ་རྟགས་འགྲེལ་ཆེན་མཁས་པའི་མགུལ་རྒྱན་མུ་རིག་འཕྲེང་མཛེས།
  author: ''
  volumes:
    85042abe938a4449be4d9f8622949a54:
      image_group_id: I1KG25182
      title: ''
      volume_number: 1
      total_pages: 218
